import { randomInArray } from "../../../../../../_mock"

const ParticipantName = [
    'Jayvion Simon',
    'Lucian Obrien',
    'Deja Brady',
    'Harrison Stein',
    'Reece Chung',
    'Lainey Davidson',
    'Cristopher Cardenas',
    'Melanie Noble',
    'Chase Day',
    'Shawn Manning',
    'Soren Durham',
    'Cortez Herring',
    'Brycen Jimenez',
    'Giana Brandt',
    'Aspen Schmitt',
    'Colten Aguilar',
    'Angelique Morse',
    'Selina Boyer',
    'Lawson Bass',
    'Ariana Lang',
    'Amiah Pruitt',
    'Harold Mcgrath',
    'Esperanza Mcintyre',
    'Mireya Conner',
    'Jamie Kline',
    'Laney Vazquez',
    'Tiffany May',
    'Dexter Shepherd',
    'Jaqueline Spencer',
    'Londyn Jarvis',
    'Yesenia Butler',
    'Jayvon Hull',
    'Izayah Pope',
    'Ayana Hunter',
    'Isabell Bender',
    'Desiree Schmidt',
    'Aidan Stout',
    'Jace Bush',
    'Janiya Williamson',
    'Hudson Alvarez',
]

const ParticipantEmailAddress = [
    'Jayvion Simon@gmail.com',
    'Lucian Obrien@gmail.com',
    'Deja Brady@gmail.com',
    'Harrison Stein@gmail.com',
    'Reece Chung@gmail.com',
    'Lainey Davidson@gmail.com',
    'Cristopher Cardenas@gmail.com',
    'Melanie Noble@gmail.com',
    'Chase Day@gmail.com',
    'Shawn Manning@gmail.com',
    'Soren Durham@gmail.com',
    'Cortez Herring@gmail.com',
    'Brycen Jimenez@gmail.com',
    'Giana Brandt@gmail.com',
    'Aspen Schmitt@gmail.com',
    'Colten Aguilar@gmail.com',
    'Angelique Morse@gmail.com',
    'Selina Boyer@gmail.com',
    'Lawson Bass@gmail.com',
    'Ariana Lang@gmail.com',
    'Amiah Pruitt@gmail.com',
    'Harold Mcgrath@gmail.com',
    'Esperanza Mcintyre@gmail.com',
    'Mireya Conner@gmail.com',
    'Jamie Kline@gmail.com',
    'Laney Vazquez@gmail.com',
    'Tiffany May@gmail.com',
    'Dexter Shepherd@gmail.com',
    'Jaqueline Spencer@gmail.com',
    'Londyn Jarvis@gmail.com',
    'Yesenia Butler@gmail.com',
    'Jayvon Hull@gmail.com',
    'Izayah Pope@gmail.com',
    'Ayana Hunter@gmail.com',
    'Isabell Bender@gmail.com',
    'Desiree Schmidt@gmail.com',
    'Aidan Stout@gmail.com',
    'Jace Bush@gmail.com',
    'Janiya Williamson@gmail.com',
    'Hudson Alvarez@gmail.com',
]

export const phoneNumber = [
    '365-374-4961',
    '904-966-2836',
    '399-757-9909',
    '692-767-2903',
    '990-588-5716',
    '955-439-2578',
    '226-924-4058',
    '552-917-1454',
    '285-840-9338',
    '306-269-2446',
    '883-373-6253',
    '476-509-8866',
    '201-465-1954',
    '538-295-9408',
    '531-492-6028',
    '981-699-7588',
    '500-268-4826',
    '205-952-3828',
    '222-255-5190',
    '408-439-8033',
    '272-940-8266',
    '812-685-8057',
    '353-801-5212',
    '606-285-8928',
    '202-767-8621',
    '222-830-0731',
    '964-940-3166',
    '262-702-2396',
    '886-261-9789',
    '352-390-5069',
    '343-907-8334',
    '575-347-2399',
    '749-228-5604',
    '774-452-2071',
    '607-841-0447',
    '395-619-2157',
    '233-834-0373',
    '586-880-2602',
    '746-772-0722',
    '638-615-3365,',
];

const _mockObject = {
    ParticipantID: (index) => `${index + 1}`,
    ParticipantName: (index) => ParticipantName[index],
    PreferName: (index) => ParticipantName[index],
    AttendanceType: (index) => '',
    EmailAddress: (index) => ParticipantEmailAddress[index],
    ContactNumber: (index) => phoneNumber[index],
    EventID: (index) => '1',
    UserID: (index) => `${index + 1000}`,
    PaymentType: (index) => `Sarawak Pay`,
    PaymentReferenceCode: (index) => '0001',
    PaymentAttachment: (index) => '',
}

export const _participant = [...Array(24)].map((_, index) => ({
    ParticipantID: `${index + 1}`,
    ParticipantName: ParticipantName[index],
    PreferName: ParticipantName[index],
    isRequiredCertificate: randomInArray([true, false]),
    Institution: randomInArray(['UCSI', 'UTS', 'UNIMAS', 'Swimburne', 'UTAR', 'UMS', 'UM']),
    AttendanceType: randomInArray(['Physical']),
    // AttendanceType: randomInArray(['Physical', 'Virtual', 'Physical & Virtual']),
    EmailAddress: ParticipantEmailAddress[index],
    ContactNumber: phoneNumber[index],
    EventID: '1',
    UserID: `${index + 1000}`,
    PaymentType: `Sarawak Pay`,
    PaymentReferenceCode: '0001',
    PaymentAttachment: '',
}));
